# Generated by Django 5.1.15 on 2026-04-14 19:29

from datetime import timedelta

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def populate_review_due_dates(apps, schema_editor):
    ReviewAssignment = apps.get_model("conference", "ReviewAssignment")
    for assignment in ReviewAssignment.objects.filter(due_at__isnull=True, completed_at__isnull=True):
        assignment.due_at = assignment.created_at + timedelta(days=14)
        assignment.save(update_fields=["due_at"])


class Migration(migrations.Migration):

    dependencies = [
        ('conference', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='reviewassignment',
            name='due_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='reviewassignment',
            name='last_reminded_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='reviewassignment',
            name='reminder_count',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='reviewer_is_available',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='reviewer_max_assignments',
            field=models.PositiveSmallIntegerField(default=6),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='reviewer_notes',
            field=models.TextField(blank=True),
        ),
        migrations.CreateModel(
            name='ReviewerTopicExpertise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('expertise', models.CharField(choices=[('LEAD', 'Lead Reviewer'), ('EXPERIENCED', 'Experienced'), ('EMERGING', 'Emerging'), ('AVOID', 'Do Not Assign')], default='EXPERIENCED', max_length=16)),
                ('notes', models.CharField(blank=True, max_length=255)),
                ('reviewer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='topic_expertise', to=settings.AUTH_USER_MODEL)),
                ('topic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviewer_expertise', to='conference.topic')),
            ],
            options={
                'ordering': ['reviewer__last_name', 'reviewer__first_name', 'topic__category', 'topic__name'],
                'unique_together': {('reviewer', 'topic')},
            },
        ),
        migrations.RunPython(populate_review_due_dates, migrations.RunPython.noop),
    ]
