# Generated by Django 5.1.15 on 2026-04-16 20:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conference', '0002_reviewassignment_due_at_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='submission',
            name='submitter_certified_authors_approved',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='submission',
            name='submitter_certified_authors_approved_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='SubmissionNotification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('kind', models.CharField(choices=[('SUBMISSION_RECEIPT', 'Submission receipt')], max_length=32)),
                ('recipient', models.EmailField(max_length=254)),
                ('subject', models.CharField(max_length=255)),
                ('note', models.CharField(blank=True, max_length=255)),
                ('sent_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='submission_notifications_sent', to=settings.AUTH_USER_MODEL)),
                ('submission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='conference.submission')),
            ],
            options={
                'ordering': ['-created_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='SubmissionSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('event_type', models.CharField(choices=[('DRAFT_SAVED', 'Draft saved'), ('SUBMITTED', 'Submitted for review'), ('RECEIPT_RESENT', 'Receipt resent'), ('PRESENTER_CONFIRMED', 'Presenter confirmed'), ('PRIZE_UPDATED', 'Prize preference updated'), ('POSTER_UPLOADED', 'Poster uploaded'), ('COPY_EDIT_COMPLETED', 'Copy edit completed')], max_length=32)),
                ('actor_label', models.CharField(blank=True, max_length=255)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('SUBMITTED', 'Submitted'), ('UNDER_REVIEW', 'Under Review'), ('REVIEWED', 'Reviewed'), ('ASSIGNED_FOR_EDIT', 'Assigned For Copy Edit'), ('EDITED', 'Edited'), ('SCHEDULED', 'Scheduled'), ('FINALIZED', 'Finalized')], max_length=32)),
                ('title', models.CharField(max_length=300)),
                ('presentation_type', models.CharField(choices=[('TALK', 'Talk'), ('POSTER', 'Poster'), ('LIGHTNING', 'Lightning Talk')], max_length=16)),
                ('abstract_text', models.TextField()),
                ('edited_abstract_text', models.TextField(blank=True)),
                ('topic_names', models.JSONField(blank=True, default=list)),
                ('author_records', models.JSONField(blank=True, default=list)),
                ('submitter_certified_authors_approved', models.BooleanField(default=False)),
                ('note', models.CharField(blank=True, max_length=255)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='submission_snapshots', to=settings.AUTH_USER_MODEL)),
                ('submission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='snapshots', to='conference.submission')),
            ],
            options={
                'ordering': ['-created_at', '-id'],
            },
        ),
    ]
